/* Gerado a partir de neural-bank.component.ts do projeto mistercontador.
   Os caminhos foram remapeados de assets/img/ para img/banks/. */
export const NAME_MAP = {
 "notalize": "Notalize",
 "bradesco": "Bradesco",
 "caixa": "Caixa Econômica Federal",
 "itau": "Itaú Unibanco",
 "sieg": "Sieg",
 "santander": "Santander",
 "sicredi": "Sicredi",
 "sicoob": "Sicoob",
 "jettax": "Jettax",
 "btg": "BTG Pactual",
 "banrisul": "Banrisul",
 "bancodobrasil": "Banco do Brasil",
 "nubank": "Nubank",
 "mercadopago": "Mercado Pago",
 "bmg": "BMG",
 "unicred": "Unicred",
 "safra": "Safra",
 "xp": "XP Investimentos",
 "bv": "Banco BV",
 "inter": "Banco Inter",
 "cora": "Cora",
 "infinitepay": "InfinitePay",
 "contabit": "Contabit",
 "brb-logo": "BRB",
 "logo-daycoval": "Daycoval",
 "banestes-nome": "Banestes",
 "banese": "Banese",
 "banpara": "Banpará",
 "banco-mercantil-novo-azul": "Banco Mercantil do Brasil",
 "logo-sofisa": "Banco Sofisa",
 "logo-banco-topazio": "Banco Topázio",
 "logotribanco-nome": "Tribanco",
 "Modobank": "Modobank",
 "c6bank": "C6 Bank",
 "neon": "Neon",
 "stone": "Stone",
 "picpay": "PicPay",
 "pagbank": "PagBank",
 "cresol": "Cresol",
 "credisis": "CrediSIS",
 "asaas": "Asaas",
 "omie": "Omie",
 "magalupay": "MagaluPay",
 "recargapay": "RecargaPay",
 "contasimples": "Conta Simples",
 "efi": "Efí (Gerencianet)",
 "original": "Banco Original",
 "votorantim": "Banco Votorantim",
 "banco-arbi": "Banco Arbi",
 "logo_bmp": "Banco BMP",
 "bib-logo": "Banco Industrial do Brasil",
 "banco-paulista": "Banco Paulista",
 "banco-pine": "Banco Pine",
 "rendimento": "Banco Rendimento",
 "bkbank-nome": "BK Bank",
 "capitual": "Capitual",
 "Zemo Bank": "Zemo Bank",
 "ailos": "Ailos",
 "duepay": "DuePay",
 "grafeno": "Grafeno",
 "iugo": "Iugu",
 "bankofamerica": "Bank of America",
 "bnb2": "Banco do Nordeste",
 "uniprime": "Uniprime",
 "sulcredi": "Sulcredi",
 "linker": "Linker",
 "beesbank": "Bees Bank",
 "ifood": "iFood Pago",
 "logo-blue": "IP4Y",
 "letsbank": "LetsBank",
 "Multiplo": "Múltiplo Bank",
 "logo-omni": "Omni",
 "paycash-logo": "PayCash",
 "pinBank": "Pinbank",
 "quality-logo-cinza": "Quality Digital Bank",
 "transfeera": "Transfeera",
 "bnp": "BNP Paribas",
 "sisprime-logo": "Sisprime",
 "squid-logo": "Squid",
 "abc": "ABC Brasil",
 "acentra_ailos": "Acentra",
 "acredicoop": "Acredicoop",
 "almah_cont": "Almah Conta",
 "artta_scd": "Artta",
 "b9_digital": "B9 Digital",
 "banco_bS2": "Banco BS2",
 "amazonia_banco": "Banco da Amazônia",
 "banco_fibra": "Banco Fibra",
 "banco_mais_todos": "Banco Mais Todos",
 "Banco_PAN": "Banco PAN",
 "xp_bank": "Banco Xip",
 "BBC_Digita": "BBC Digital",
 "BDigital": "BDigital",
 "Bling": "Bling",
 "Bocom_BBM": "Bocom BBM",
 "brinks_pay": "Brinks Pay",
 "bs_bank": "BS Bank",
 "caruana_banco": "Caruana",
 "celcoin": "Celcoin",
 "Civia_banco": "Civia",
 "clara_banco": "Clara",
 "condoconta": "Condoconta",
 "Confianza_Empresarial": "Confianza Empresarial",
 "Conta_Azul": "Conta Azul",
 "Contabilizei_Bank": "Contabilizei Bank",
 "Conta_Pronta": "Conta Pronta",
 "Contbank": "Contbank",
 "Cred_Crea": "Cred Crea",
 "Credelesc": "Credelesc",
 "Credicomin": "Credicomin",
 "Credicoopavel": "Credicoopavel",
 "Credifoz": "Credifoz",
 "Credisan": "Credisan",
 "Crevisc": "Crevisc",
 "Delfinance": "Delfinance",
 "Dock": "Dock",
 "Everblue": "Everblue",
 "Evolua": "Evolua",
 "FF_Cred": "FF Cred",
 "FIBank": "FIBank",
 "Fiducia_SCM": "Fidúcia SCM",
 "Five_bank": "Five",
 "Flash": "Flash",
 "GC_Pay": "GC Pay",
 "Gobank": "Gobank",
 "Greencred": "Greencred",
 "Hinova_Pay": "Hinova Pay",
 "Hotmart": "Hotmart",
 "ID_Banco_Digital": "ID Banco Digital",
 "Ideal_Banking": "Ideal Banking",
 "Inovanti": "Inovanti",
 "Invest_Bravo": "Invest Bravo",
 "Iriom": "Iriom",
 "Kamino": "Kamino",
 "LiveBank": "LiveBank",
 "Logisbank": "Logisbank",
 "Makena": "Makena",
 "MaviBank": "MaviBank",
 "mentore_logo": "Mentore Bank",
 "MFUG_Brasil": "MFUG Brasil",
 "Mizuho": "Mizuho",
 "ModaBank": "ModaBank",
 "Mosaico_Pay": "Mosaico Pay",
 "MSC_Bank": "MSC Bank",
 "Olist_tiny": "Olist / Tiny",
 "Onfly": "Onfly",
 "Onlyup": "Onlyup",
 "OrionPag": "OrionPag",
 "OWL_Digital": "OWL Digital",
 "Pagnex_Bank": "Pagnex Bank",
 "Pagô": "Pagô",
 "Pague_Veloz": "Pague Veloz",
 "PayPal": "PayPal",
 "PJ_Bank": "PJ Bank",
 "Prover_Avancard": "Prover / Avancard",
 "Prudential_Bank": "Prudential Bank",
 "PX_Bank": "PX Bank",
 "QI_SCD": "QI SCD",
 "Ribeirao_Preto": "Ribeirão Preto",
 "SBCash": "SBCash",
 "Sefer_Bank": "Sefer Bank",
 "Semear": "Semear",
 "Shield": "Shield",
 "Shoppe_Pay": "Shoppe Pay",
 "Sifrabank": "Sifrabank",
 "Somapay": "Somapay",
 "SpotBank": "SpotBank",
 "Stark_Bank": "Stark Bank",
 "SumUp_Bank": "SumUp Bank",
 "Taipa": "Taipa",
 "Teddy": "Teddy",
 "Thomson_Reuters": "Thomson Reuters",
 "Transpocred": "Transpocred",
 "Truck_Digital": "Truck Digital",
 "Unilos": "Unilos",
 "UY3": "UY3",
 "Uzzipay": "Uzzipay",
 "Valori": "Valori",
 "Vexpenses": "Vexpenses",
 "Viacredi": "Viacredi",
 "Villela_bank": "Villela Brasil Bank",
 "Voltz_Empresas": "Voltz Empresas",
 "Wide_Pay": "Wide Pay",
 "ZeitBank": "ZeitBank"
};

export const TIERS = [
 {
  "radius": 17,
  "appearBeyond": null,
  "logos": [
   "img/banks/Conta_Azul.jpg",
   "img/banks/notalize.jpg",
   "img/banks/bradesco.svg",
   "img/banks/caixa.svg",
   "img/banks/itau.svg",
   "img/banks/sieg.jpg",
   "img/banks/santander.svg",
   "img/banks/sicredi.svg",
   "img/banks/sicoob.svg",
   "img/banks/jettax.jpg",
   "img/banks/btg.svg",
   "img/banks/banrisul.svg",
   "img/banks/bancodobrasil.svg",
   "img/banks/nubank.svg",
   "img/banks/mercadopago.svg",
   "img/banks/bmg.svg",
   "img/banks/unicred.svg",
   "img/banks/safra.svg",
   "img/banks/xp.svg",
   "img/banks/bv.svg",
   "img/banks/inter.svg",
   "img/banks/cora.svg",
   "img/banks/infinitepay.svg",
   "img/banks/contabit.png",
   "img/banks/brb-logo.svg",
   "img/banks/logo-daycoval.svg",
   "img/banks/banestes-nome.svg",
   "img/banks/banese.svg",
   "img/banks/banpara.svg",
   "img/banks/banco-mercantil-novo-azul.svg",
   "img/banks/logo-sofisa.svg",
   "img/banks/logo-banco-topazio.svg",
   "img/banks/logotribanco-nome.svg",
   "img/banks/Modobank.svg"
  ]
 },
 {
  "radius": 27,
  "appearBeyond": 52,
  "logos": [
   "img/banks/c6bank.svg",
   "img/banks/neon.svg",
   "img/banks/stone.svg",
   "img/banks/picpay.svg",
   "img/banks/pagbank.svg",
   "img/banks/cresol.svg",
   "img/banks/credisis.svg",
   "img/banks/asaas.svg",
   "img/banks/omie.svg",
   "img/banks/magalupay.svg",
   "img/banks/recargapay.svg",
   "img/banks/contasimples.svg",
   "img/banks/efi.svg",
   "img/banks/original.svg",
   "img/banks/votorantim.svg",
   "img/banks/banco-arbi.svg",
   "img/banks/logo_bmp.svg",
   "img/banks/bib-logo.svg",
   "img/banks/banco-paulista.svg",
   "img/banks/banco-pine.svg",
   "img/banks/rendimento.svg",
   "img/banks/bkbank-nome.svg",
   "img/banks/capitual.svg",
   "img/banks/Zemo Bank.svg"
  ]
 },
 {
  "radius": 38,
  "appearBeyond": 65,
  "logos": [
   "img/banks/ailos.svg",
   "img/banks/duepay.svg",
   "img/banks/grafeno.svg",
   "img/banks/iugo.svg",
   "img/banks/bankofamerica.svg",
   "img/banks/bnb2.svg",
   "img/banks/uniprime.svg",
   "img/banks/sulcredi.svg",
   "img/banks/linker.svg",
   "img/banks/beesbank.svg",
   "img/banks/ifood.png",
   "img/banks/logo-blue.svg",
   "img/banks/letsbank.svg",
   "img/banks/Multiplo.svg",
   "img/banks/logo-omni.svg",
   "img/banks/paycash-logo.svg",
   "img/banks/pinBank.svg",
   "img/banks/quality-logo-cinza.svg",
   "img/banks/transfeera.svg",
   "img/banks/bnp.svg",
   "img/banks/sisprime-logo.svg",
   "img/banks/squid-logo.svg"
  ]
 },
 {
  "radius": 50,
  "appearBeyond": 80,
  "logos": [
   "img/banks/abc.png",
   "img/banks/acentra_ailos.jpg",
   "img/banks/acredicoop.jpg",
   "img/banks/almah_cont.png",
   "img/banks/artta_scd.jpg",
   "img/banks/b9_digital.jpg",
   "img/banks/banco_bS2.png",
   "img/banks/amazonia_banco.jpg",
   "img/banks/banco_fibra.jpg",
   "img/banks/banco_mais_todos.jpg",
   "img/banks/Banco_PAN.png",
   "img/banks/xp_bank.png",
   "img/banks/BBC_Digita.png",
   "img/banks/BDigital.png",
   "img/banks/Bling.jpg",
   "img/banks/Bocom_BBM.png",
   "img/banks/brinks_pay.png",
   "img/banks/bs_bank.png",
   "img/banks/caruana_banco.jpg",
   "img/banks/celcoin.png",
   "img/banks/Civia_banco.png",
   "img/banks/clara_banco.png",
   "img/banks/condoconta.jpg",
   "img/banks/Confianza_Empresarial.png",
   "img/banks/Contabilizei_Bank.jpg",
   "img/banks/Conta_Pronta.png",
   "img/banks/Contbank.png",
   "img/banks/Cred_Crea.png",
   "img/banks/Credelesc.jpg",
   "img/banks/Credicomin.png",
   "img/banks/Credicoopavel.jpg",
   "img/banks/Credifoz.png",
   "img/banks/Credisan.png",
   "img/banks/Crevisc.png",
   "img/banks/Delfinance.jpg",
   "img/banks/Dock.png",
   "img/banks/Everblue.jpg",
   "img/banks/Evolua.png",
   "img/banks/FF_Cred.jpg",
   "img/banks/FIBank.png",
   "img/banks/Fiducia_SCM.jpg",
   "img/banks/Five_bank.jpg",
   "img/banks/Flash.png",
   "img/banks/GC_Pay.png",
   "img/banks/Gobank.jpg",
   "img/banks/Greencred.jpg",
   "img/banks/Hinova_Pay.jpg",
   "img/banks/Hotmart.png",
   "img/banks/ID_Banco_Digital.jpg",
   "img/banks/Ideal_Banking.jpg",
   "img/banks/Inovanti.jpg",
   "img/banks/Invest_Bravo.jpg",
   "img/banks/Iriom.jpg",
   "img/banks/Kamino.jpg",
   "img/banks/LiveBank.png",
   "img/banks/Logisbank.png",
   "img/banks/Makena.png",
   "img/banks/MaviBank.png",
   "img/banks/mentore_logo.jpg",
   "img/banks/MFUG_Brasil.png",
   "img/banks/Mizuho.png",
   "img/banks/ModaBank.jpg",
   "img/banks/Mosaico_Pay.jpg",
   "img/banks/MSC_Bank.png",
   "img/banks/Olist_tiny.jpeg",
   "img/banks/Onfly.jpg",
   "img/banks/Onlyup.png",
   "img/banks/OrionPag.jpg",
   "img/banks/OWL_Digital.png",
   "img/banks/Pagnex_Bank.png",
   "img/banks/Pagô.png",
   "img/banks/Pague_Veloz.jpg",
   "img/banks/PayPal.jpg",
   "img/banks/PJ_Bank.png",
   "img/banks/Prover_Avancard.png",
   "img/banks/Prudential_Bank.png",
   "img/banks/PX_Bank.jpg",
   "img/banks/QI_SCD.png",
   "img/banks/Ribeirao_Preto.png",
   "img/banks/SBCash.png",
   "img/banks/Sefer_Bank.png",
   "img/banks/Semear.png",
   "img/banks/Shield.png",
   "img/banks/Shoppe_Pay.png",
   "img/banks/Sifrabank.png",
   "img/banks/Somapay.jpg",
   "img/banks/SpotBank.jpg",
   "img/banks/Stark_Bank.png",
   "img/banks/SumUp_Bank.png",
   "img/banks/Taipa.jpg",
   "img/banks/Teddy.jpg",
   "img/banks/Thomson_Reuters.png",
   "img/banks/Transpocred.png",
   "img/banks/Truck_Digital.jpg",
   "img/banks/Unilos.png",
   "img/banks/UY3.png",
   "img/banks/Uzzipay.png",
   "img/banks/Valori.png",
   "img/banks/Vexpenses.png",
   "img/banks/Viacredi.png",
   "img/banks/Villela_bank.png",
   "img/banks/Voltz_Empresas.jpg",
   "img/banks/Wide_Pay.jpg",
   "img/banks/ZeitBank.png"
  ]
 }
];
